version: 0.2
 
phases:
  install:
    runtime-versions:
      java: corretto17  # Ensure Java 17 is installed
  build:
    commands:
      - echo "Compiling Java HTTP Server..."
- javac HttpFileServer.java  # Compile Java file
  post_build:
    commands:
      - echo "Starting Java HTTP Server..."
      - nohup java HttpFileServer &  # Run in the background
 
artifacts:
  files:
    - '**/*'